---

- hosts: all
  become: true
  remote_user: keith 
  vars:
    ansible_private_key_file: "~/.ssh/id_ed25519"
  pre_tasks:

  - name: remove cdrom from sources (Debian & Ubuntu)
    tags: always
    replace:
      dest: /etc/apt/sources.list
      regexp: '^deb cdrom'
      replace: '#deb cdrom'
    when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

  - name: update cache (AlmaLinux & CentOS)
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS" or ansible_distribution == "AlmaLinux"
    changed_when: false

  - name: update cache (Debian & Ubuntu)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    changed_when: false

- hosts: all
  become: true
  remote_user: keith
  vars:
    ansible_private_key_file: "~/.ssh/id_ed25519"
  tasks:

  - name: create ansible user
    tags: always
    user:
      name: ansible
      groups: root

  - name: add ssh key for ansible
    tags: always
    authorized_key:
      user: ansible
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEwQ/H8W9/1/y+0mldRq4wnvcQ3Bzuyfj3JRotCttCPz ansible"

  - name: add sudoers file for ansible
    tags: always
    copy:
      src: ~/ansible/files/sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

- hosts: all
  become: true
  roles:
    - base

- hosts: container_servers
  become: true
  roles:
    - container_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: media_servers
  become: true
  roles:
    - media_servers

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: workstations
  become: true
  roles:
    - workstations
