---

- hosts: all
  become: true
  pre_tasks:
  - name: update cache (AlmaLinux & CentOS)
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS" or ansible_distribution == "AlmaLinux"
    changed_when: false

  - name: update cache (Debian & Ubuntu)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    changed_when: false

- hosts: all
  become: true
  roles:
    - base

- hosts: container_servers
  become: true
  roles:
    - container_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: media_servers
  become: true
  roles:
    - media_servers

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: workstations
  become: true
  roles:
    - workstations
