---

- hosts: all

- hosts: all
  become: true
  tags: always
  tasks:

    - name: creates ansible user
      tags: always
      user:
        name: ansible
        groups: root

    - name: add ssh key for ansible
      tags: always
      authorized_key:
        user: ansible
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEwQ/H8W9/1/y+0mldRq4wnvcQ3Bzuyfj3JRotCttCPz ansible"

    - name: add sudoers file for ansible
      tags: always
      copy:
        src: sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440
