---

- hosts: all
  become: true
  pre_tasks:
  - name: update cache (CentOS)
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"
    changed_when: false

  - name: update cache (Debian & Ubuntu)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    changed_when: false

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Debian & Ubuntu)
    tags: always
    apt:
      upgrade: dist
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"


- hosts: all
  become: true
  tasks:

  - name: copy tmux config
    tags: always
    copy:
      src: ~/ansible/files/tmux.conf
      dest: /home/keith/.tmux.conf
      owner: keith
      group: keith
      mode: 0644

  - name: add IP addresses of all hosts to all hosts
    tags: always
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"
