- name: install tmux and vim
  tags: always
  package:
    name:
      - "{{ tmux_package_name }}"
      - "{{ vim_package_name }}"
    state: latest

- name: copy tmux config
  tags: always
  copy:
    src: ~/ansible/files/tmux.conf
    dest: /home/keith/.tmux.conf
    owner: keith
    group: keith
    mode: 0644

- name: add IP addresses of all hosts to all hosts
  tags: always
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
