- name: install updates (AlmaLinux & CentOS)
  tags: always
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == "CentOS" or ansible_distribution == "AlmaLinux"

- name: install updates (Debian & Ubuntu)
  tags: always
  apt:
    upgrade: dist
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: install tmux and vim
  tags: always
  package:
    name:
      - "{{ tmux_package_name }}"
      - "{{ vim_package_name }}"
    state: latest
  when: ansible_distribution == "AlmaLinux" or ansible_distribution == "CentOS" or ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: copy tmux config
  tags: always
  copy:
    src: ~/ansible/files/tmux.conf
    dest: /home/keith/.tmux.conf
    owner: keith
    group: keith
    mode: 0644

- name: add IP addresses of all hosts to all hosts
  tags: always
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: check if reboot is required (AlmaLinux & CentOS) and reboot if necessary
  ansible.builtin.shell:
    cmd: "needs-restarting -r -s"
  register: needs_restarting
  changed_when: needs_restarting.rc == 1
  failed_when: false
  notify: reboot_needed
  when: ansible_distribution == "AlmaLinux" or ansible_distribution == "CentOS"

- name: check if reboot is required (Debian & Ubuntu) and reboot if necessary
  stat: path=/var/run/reboot-required
  register: reboot_required
  changed_when: reboot_required.stat.exists
  notify: reboot_needed
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
